version: 2.1
jobs:
  build:
    docker:
      - image: docker:19.03.12-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push application Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t dmytrovelychkodev/nestjs-api-template:$TAG .
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push dmytrovelychkodev/nestjs-api-template:$TAG
  deploy:
    docker:
      - image: node:12.18-alpine
    steps:
      - run:
          name: Pulling image
          command: |
            echo 'docker pull'

orbs:
  node: circleci/node@3.0.0

workflows:
  test_build_deploy_master:
    jobs:
      - node/test
      - build:
          requires:
            - node/test
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
